### ISSUE TITLE
Cropping left and right parts of image for VIT input

### ISSUE THREAD

**Issue by chaitanya100100** [shubham-goel/4D-Humans#13]
Hello,
Thanks for publishing this extremely well-written code. I was going through the VIT setup in your model and noticed this (https://github.com/shubham-goel/4D-Humans/blob/5e48b04cfd094f3e62beb2f16421394dafd68843/hmr2/models/hmr2.py#L105) line where you are cropping 32 pixels from left and right. Is there any particular reason for that? As far as I can tell, there is no precautionary padding for this and this may crop out parts of human (especially when the person is horizontal).

**Comment by shubham-goel** [comment]
Hi Chaitanya, thanks for pointing this out and your patience!

We crop 32 pixels on either side to use a [ViTPose](https://github.com/ViTAE-Transformer/ViTPose) initialized transformer backbone. 

We have padding code ([here](https://github.com/shubham-goel/4D-Humans/blob/0e58d8c92a69e1d93e0f8f4ad450bb1d543dd0e8/hmr2/datasets/image_dataset.py#L234)) but it wasn't being called because of a missing config option. We've fixed that now.
