### ISSUE TITLE
4D-Humans root vs SMPL root 

### ISSUE THREAD

**Issue by aidilayce** [shubham-goel/4D-Humans#138]
Hello,

Thank you for the amazing work!

Do you define the camera translation (`pred_cam_t_full`) from the pelvis or the midhip? I'm trying to obtain the predicted 3D joint positions in the world frame but having some translation issues. I thought there might be a difference between 4D-Humans root joint and SMPL root joint after checking [joint ids](https://github.com/nkolot/SPIN/blob/2476c436013055be5cb3905e4e4ecfa86966fac3/constants.py#L16) .  

For instance, to get the root translation in world frame, I'm doing
`world_root_translation = (Rw[0].T @ (pred_cam_t_full - Tw[0].unsqueeze(0)).T).T ` where `Rw` and `Tw` are the rotation and translation matrices of my camera, and I directly use the `pred_cam_t_full` directly from 4D-Humans prediction. I also modified the focal length according to the camera I'm using. This gives me an inaccurate translation though. So, I thought there might be some mismatch between the SMPL root and 4D-Humans root for pred_cam_t_full value.

**Comment by geopavlakos** [comment]
4D Humans have the same root as SMPL. However, please note that the root of SMPL is not at the origin of the SMPL coordinate frame, so that could create problems with your calculations.

**Comment by aidilayce** [comment]
Yep, that was the problem. Thank you!

**Comment by jjd1123** [comment]
@geopavlakos 

Hello，

If I understand right, `pred_cam_t_full` is the position of the root in the camera space. So if I want to project the human joints onto the original image coordinate system, should I set the root joint's position to `pred_cam_t_full` directly, instead of just adding it to the joint positions?

However, I'm a bit confused because [here](https://github.com/shubham-goel/4D-Humans/blob/6ec79656a23c33237c724742ca2a0ec00b398b53/hmr2/models/hmr2.py#L135) you simply add `pred_cam_t` to all the joints. Could you please explain what issues might arise from the difference between the root and the origin?

Thank you very much!
