### ISSUE TITLE
Possibility to convert the 3D mesh into point cloud

### ISSUE THREAD

**Issue by JefferyChen453** [shubham-goel/4D-Humans#98]
I am attempting to perform action recognition in 3D space. Is it possible to reconstruct the 3*N vertices of the human mesh back to real-world scale point cloud coordinates by leveraging shape information predicted by the predictor _f(I)_?

**Comment by geopavlakos** [comment]
We estimate the human mesh and the [location in the camera space](https://github.com/shubham-goel/4D-Humans/blob/124e8b2dc041fdd7e02f879ce851952cb810636b/demo.py#L94). The location estimate might be inaccurate because of the scale ambiguity, but you can check if it's satisfactory for your application.

By the way, if you are interested in action recognition using human mesh recovery, please consider taking a look at our related work: https://github.com/brjathu/LART
